### ISSUE TITLE
social costmap plugin problem in humble

### ISSUE THREAD

**Issue by dharanish-nh** [robotics-upo/nav2_social_costmap_plugin#1]
I am using your Foxy package to run in humble. while doing so I stumbled upon some problems. I was hoping you could help me out with this issue.

1. Cloning it directly to the workspace. Then trying to colcon build gives an error as follows.
`/ppl_sub_ = node_->create_subscription<people_msgs::msg::People>(
      "/people", rclcpp::SensorDataQoS(),
      std::bind(&SocialLayer::peopleCallback, this, std::placeholders::_1));

/home/bot/humble_ws/src/nav2_social_costmap_plugin/src/social_layer.cpp:36:20: error: base operand of ‘->’ has non-pointer type ‘rclcpp_lifecycle::LifecycleNode::WeakPtr’ {aka ‘std::weak_ptr<rclcpp_lifecycle::LifecycleNode>’}    36 |   RCLCPP_INFO(node_->get_logger() `

2. According to the error I changed "node_" to "node_.lock()". then I get no errors while building. But when I run the simulation the robot does not navigate and does not show any errors. here is a video [https://www.youtube.com/watch?v=FY26voZv02E](url) . [https://www.youtube.com/watch?v=FY26voZv02E]

3. modified code snippets 

i.`ppl_sub_= node_.lock()->create_subscription<people_msgs::msg::People>(
      "/people", rclcpp::SensorDataQoS(),
      std::bind(&SocialLayer::peopleCallback, this, `std::placeholders::_1));

  RCLCPP_INFO(node_.lock()->get_logger(),
              "SocialLayer: subscribed to "
              "topic %s",
              ppl_sub_->get_topic_name());`
              
ii. `void SocialLayer::get_parameters() {
  node_.lock()->get_parameter(name_ + "." + "enabled", enabled_);
  node_.lock()->get_parameter(name_ + "." + "cutoff", cutoff_);
  node_.lock()->get_parameter(name_ + "." + "amplitude", amplitude_);
  node_.lock()->get_parameter(name_ + "." + "covariance_front_height",
                       sigma_front_height_);
  node_.lock()->get_parameter(name_ + "." + "covariance_front_width",
                       sigma_front_width_);
  node_.lock()->get_parameter(name_ + "." + "covariance_rear_height",
                       sigma_rear_height_);
  node_.lock()->get_parameter(name_ + "." + "covariance_rear_width",
                       sigma_rear_width_);
  node_.lock()->get_parameter(name_ + "." + "covariance_right_height",
                       sigma_right_height_);
  node_.lock()->get_parameter(name_ + "." + "covariance_right_width",
                       sigma_right_width_);
  node_.lock()->get_parameter(name_ + "." + "covariance_when_still",
                       sigma_when_still_);
  node_.lock()->get_parameter(name_ + "." + "use_passing", use_passing_);
  node_.lock()->get_parameter(name_ + "." + "use_vel_factor", use_vel_factor_);
  node_.lock()->get_parameter(name_ + "." + "speed_factor_multiplier", speed_factor_);
  node_.lock()->get_parameter(name_ + "." + "publish_occgrid", publish_occgrid_);
}`   

I kindly request you help me out in understanding this issue. @noeperez

**Comment by noeperez** [comment]
Hi!
It is very difficult to me to know the error since I have not check the plugin in Humble. 
We will make the Humble version but that will not be soon.   
Sorry, I can not help you for the moment.

**Comment by noeperez** [comment]
Hey @dharanish-nh,
probably it is too late, but finally we adapted the code to Humble (default branch now). Now we have available the plugin for Foxy and Humble distros.

**Comment by dharanish-nh** [comment]
Hey @noeperez ,
unfortunately, I finished the project recently with an alternative solution. Thank you now I can check how it works with the social layer.
